name: Sentinel-FS Kernel Test
on: [push]

jobs:
  test-sentinel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libbpf-dev libelf-dev \
            linux-tools-common linux-tools-generic linux-tools-$(uname -r) python-is-python3

            if [ -f /usr/lib/linux-tools/*/bpftool ]; then
              sudo ln -sf /usr/lib/linux-tools/*/bpftool /usr/local/bin/bpftool
            fi

      - name: Build Sentinel-FS
        run: make

      - name: Run Ransomware Simulator
        run: |
          # Create a script that writes high-entropy data (from /dev/urandom)
          cat << 'EOF' > sim_ransom.py
          import os
          import time
          with open("test_file.enc", "wb") as f:
              for _ in range(1000):
                  f.write(os.urandom(4096))
                  f.flush()
                  print("Malicious write...")
                  time.sleep(0.01)
          EOF
          # Run it in the background
          python3 sim_ransom.py &
          echo "SIM_PID=$!" >> $GITHUB_ENV
          sudo timeout 20s ./sentinel > output.log || [ $? -eq 124 ]
          if grep -p "BLOCK:" output.log; then
            echo "Pass! logs:\n"
            cat output.log
          else
            echo "Fail! logs:\n"
            cat output.log
            exit 1
          fi
      
      - name: Check dmesg on fail
        if: failure()
        run: sudo dmesg | tail -n 50
