name: Sentinel-FS Kernel Test
on: [push]

jobs:
  test-sentinel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libbpf-dev libelf-dev \
            linux-tools-common linux-tools-generic linux-tools-$(uname -r) python-is-python3

            if [ -f /usr/lib/linux-tools/*/bpftool ]; then
              sudo ln -sf /usr/lib/linux-tools/*/bpftool /usr/local/bin/bpftool
            fi

      - name: Build Sentinel-FS
        run: make

      - name: Run Test Suite
        run: |
          # 1. Clear kernel logs
          sudo dmesg -C

          sudo stdbuf -oL ./sentinel > output.log 2>&1 &
          SENTINEL_PID=$!
          
          # Give the BPF 3 seconds to start
          sleep 3

          cat << 'EOF' > sim_ransom.py
          import os, time
          print("Starting malicious writes...")
          for i in range(100):
              with open(f"test_{i}.enc", "wb") as f:
                  f.write(os.urandom(8192))
                  f.flush()
              time.sleep(0.05)
          EOF
          
          python3 sim_ransom.py
          
          # 4. Give Sentinel a moment to process the last writes
          sleep 2
          
          # 5. Stop Sentinel and check logs
          sudo kill $SENTINEL_PID || true
          
          if grep -q "BLOCK:" output.log; then
            echo "Pass! Sentinel detected the threat."
            cat output.log
          else
            echo "Fail! No detection found."
            cat output.log
            exit 1
          fi
      
      - name: Check dmesg on fail
        if: failure()
        run: sudo dmesg
